import React from 'react'
import './styles.scss'

const textBlocks: string[] = [
  'For centuries, civilizations have sought to understand the universe through religion, philosophy, and science. Long before telescopes, particle accelerators, and genetic sequencing, ancient texts contained descriptions of reality that, at first glance, seemed poetic or allegorical. But as modern science has advanced, we now see striking <strong>parallels between ancient wisdom and contemporary discoveries</strong>—raising profound questions about the nature of knowledge itself. Consider the <strong>expansion of the universe</strong>, which was only confirmed in the 20th century through Hubble’s redshift observations. Yet, the Quran (51:47) states, “And the heaven We constructed with strength, and indeed, We are [its] expander.” Hindu cosmology also describes <strong>Brahmanda</strong>, the expanding cosmic egg, conceptually resembling the idea of an <strong>inflationary universe</strong>. Did these texts intuitively grasp fundamental physical laws long before modern cosmology, or is this an example of retrospective interpretation?',
  'The <strong>Big Bang Theory</strong>, now the leading scientific explanation for the universe’s origin, describes a singularity expanding outward. This aligns with religious texts that speak of a <strong>moment of creation where all existence was once unified before being separated</strong>. The Quran (21:30) states, “The heavens and the earth were once joined together before We split them apart.” Similarly, the <strong>cosmic singularity hypothesis</strong> echoes the Biblical phrase, “Let there be light” (Genesis 1:3), which could be metaphorically linked to <strong>the first burst of electromagnetic radiation</strong> following cosmic inflation. Even more striking is the discovery of <strong>cosmic microwave background radiation (CMBR)</strong> in 1965, which scientists consider the <strong>thermal echo of the Big Bang</strong>. Many ancient texts describe a <strong>primordial void followed by an era of light</strong>, eerily resembling the <strong>transition from the opaque, plasma-filled early universe to the transparent cosmos we observe today</strong>.',
  'In the realm of <strong>quantum mechanics</strong>, modern physics proposes the existence of <strong>parallel universes, extra-dimensional space, and non-locality</strong>, concepts that were once the domain of mysticism and metaphysics. Buddhist and Hindu cosmologies describe multiple planes of existence that bear similarities to <strong>the Many-Worlds Interpretation</strong> of <strong>quantum mechanics</strong>, where every possible outcome of an event exists in a separate, parallel reality. Even in neuroscience, ideas that were once purely philosophical—such as <strong>the mind-body dualism of Descartes or the Buddhist concept of consciousness as an emergent phenomenon</strong>—are now being explored through <strong>brain mapping, neuroplasticity, and AI-driven cognitive models.</strong>',
  'MILO is designed to <strong>explore these intersections at scale</strong>. As an <strong>AI-powered, open-source protocol</strong>, MILO systematically analyzes <strong>historical, theological, and scientific texts,</strong> identifying <strong>patterns and correlations that might otherwise go unnoticed</strong>. Unlike proprietary AI systems, MILO is <strong>modular, transparent, and community-driven</strong>, built on <strong>FastAPI with an interchangeable LLM backend</strong> (currently OpenAI GPT, but designed for model-agnostic adaptability). MILO’s open framework allows researchers, developers, and domain experts to <strong>expand its datasets, fine-tune AI models, and create new tools for knowledge discovery</strong>. By structuring ancient and modern insights into machine-readable data, MILO transforms historical inquiry into <strong>a dynamic and scalable AI-assisted research platform</strong>.',
  'The challenge MILO addresses is the <strong>epistemic fragmentation between science, history, and philosophy</strong>. Modern intellectual discourse is divided into <strong>scientific empiricism and historical-metaphysical traditions</strong>, with little effort to synthesize their insights systematically. Religious and philosophical texts often provide <strong>moral, existential, and cosmological perspectives</strong>, but they are frequently <strong>dismissed in scientific communities</strong> due to their allegorical nature. Conversely, <strong>scientific breakthroughs frequently validate or align with philosophical and theological ideas</strong>, yet they remain siloed from the cultural narratives that shaped humanity’s understanding of the world. MILO seeks to bridge this divide through <strong>AI-driven pattern recognition and contextual analysis</strong>, allowing users to explore <strong>thematic and semantic parallels across disciplines</strong>, fostering data-driven discussions rather than ideological debates.',
  'Artificial Intelligence, particularly <strong>Natural Language Processing (NLP)</strong>, has revolutionized <strong>textual analysis and comparative research</strong>. MILO applies <strong>large language models (LLMs) to extract semantic structures, identify recurring motifs, and compare thematic frameworks</strong> across historical, theological, and scientific texts. This AI-driven hermeneutic approach enables MILO to analyze <strong>metaphors, symbolic patterns, and conceptual overlaps, revealing underlying structures of knowledge that persist across civilizations and disciplines</strong>. Comparative epistemology plays a key role in this framework, helping MILO contextualize how <strong>human understanding has evolved over time, demonstrating convergence points between ancient perspectives and modern discoveries</strong>. Rather than treating religious and historical texts as static archives, MILO transforms them into a <strong>continuously evolving knowledge framework</strong>.',
  'MILO’s <strong>technical architecture</strong> is designed for <strong>scalability, flexibility, and modularity</strong>, ensuring compatibility with multiple AI models and data sources. Its <strong>FastAPI backend</strong> provides <strong>high-speed processing and efficient API integration</strong>, while its <strong>model-agnostic framework</strong> supports <strong>various LLMs</strong>, including OpenAI GPT, Cohere, Anthropic Claude, and <strong>fine-tuned open-source models like Llama, Falcon, and Mistral</strong>. Users can upload <strong>historical documents, religious scriptures, and scientific papers</strong>, allowing MILO’s dataset to grow organically. However, MILO currently <strong>lacks a formal validation protocol</strong>, as it relies on <strong>prebuilt LLM APIs</strong> rather than a self-verifying AI framework. The open-source community is encouraged to <strong>develop validation layers, citation-tracking tools, and bias-mitigation strategies</strong> to enhance interpretive accuracy.',
  'Beyond theoretical applications, MILO has profound implications for <strong>scientific research, legal history, and cross-cultural analysis</strong>. AI-assisted medical research could compare <strong>ancient medicinal texts from Ayurveda, Chinese medicine, and Greco-Roman pharmacology to detect recurring treatments, formulations, and diagnostic methods that align with modern biomedical findings</strong>. In legal studies, MILO could be used to <strong>trace the evolution of constitutional frameworks across civilizations</strong>, helping legal scholars <strong>compare ancient legal doctrines with modern jurisprudence</strong>. By structuring historical knowledge into machine-readable data, MILO becomes a tool for academic research, policy analysis, and epistemic refinement rather than just an intellectual curiosity.',
  'Despite its promise, MILO faces significant challenges. NLP models still struggle with <strong>metaphors, allegories, and theological ambiguity</strong>, which can lead to misinterpretations. Engaging religious scholars in AI-assisted textual analysis presents <strong>cultural and ethical considerations</strong>, requiring ongoing dialogue between <strong>AI researchers, historians, and philosophers</strong>. Future development will focus on <strong>peer-reviewed validation mechanisms, multimodal AI models integrating text, image, and audio analysis, and decentralized governance models for dataset curation</strong>. By implementing these enhancements, MILO can evolve from <strong>a knowledge retrieval engine into a sophisticated epistemic framework</strong>, respecting the nuances of historical, theological, and philosophical traditions while maintaining scientific rigor.',
  'MILO is more than just an AI system—it is <strong>an evolving, open-source knowledge protocol</strong>. Unlike proprietary AI models restricted by corporate oversight, MILO is <strong>community-driven</strong>, allowing users to fork the protocol, modify its AI models, and expand its datasets to refine AI-generated insights. Its decentralized approach ensures that knowledge production remains transparent, extensible, and adaptable to different academic and cultural contexts. MILO represents a paradigm shift in AI-assisted epistemology, where knowledge is not merely consumed but co-created by a global network of researchers, developers, and scholars. As MILO grows, it has the potential to <strong>transform how civilizations engage with their histories, bridging scientific, philosophical, and theological insights like never before</strong>. The question is no longer whether this knowledge should be explored—it is <strong>who will take part in uncovering it</strong>.'
]

const Thesis: React.FC = () => {
  return (
    <div id='thesis' className='thesis-container'>
      <h2>How Milo Works</h2>
      {textBlocks.map((item, index) => (
        <div key={index} dangerouslySetInnerHTML={{ __html: item }} className='thesis-container__text-block' />
      ))}
    </div>
  )
}

export default Thesis